name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale and made be closed by maintainers if there is no additional activity within a week.'
        stale-pr-message: 'This pull request has been marked as stale and made be closed by maintainers if there is no additional activity within a week.'
        stale-issue-label: 'STALE'
        stale-pr-label: 'STALE'
